import { Platform } from 'react-native';

export const colors = {
  light: {
    background: '#F8FAFF',
    card: '#fff',
    text: '#0F172A',
    textSecondary: '#64748B',
    primary: '#1D4ED8',
    avatarBg: '#EFF6FF',
    border: '#E2E8F0',
    iconBlueBg: '#E0F2FE',
    iconBlue: '#1D4ED8',
    iconSlateBg: '#E2E8F0',
    iconSlate: '#334155',
    iconGreenBg: '#DCFCE7',
    iconGreen: '#047857',
    iconRedBg: '#FEE2E2',
    iconRed: '#DC2626',
    iconOrangeBg: '#FFF3EA',
    iconOrange: '#FF8C42',
    iconPurpleBg: '#F3E8FF',
    iconPurple: '#8338EC',
    iconPinkBg: '#FFE8F0',
    iconPink: '#FF006E',
    iconTealBg: '#E6FFFA',
    iconTeal: '#2EC4B6',
    iconGrayBg: '#F1F5F9',
    iconGray: '#6C757D',
    sheetBg: '#ffffff',
    sheetItemBg: '#f8fafc',
    sheetDrag: '#e2e8f0',
    textPrimarySheet: '#2563eb',
    textCancel: 'grey',
    switchTrackFalse: '#CBD5E1',
    buttonText: '#fff',
    tabIconDefault: '#687076',
    tabIconSelected: '#1D4ED8',
  },
  dark: {
    background: '#0F172A',
    card: '#1E293B',
    text: '#F8FAFC',
    textSecondary: '#94A3B8',
    primary: '#3B82F6',
    avatarBg: '#1E3A8A',
    border: '#334155',
    iconBlueBg: '#1E3A8A',
    iconBlue: '#60A5FA',
    iconSlateBg: '#334155',
    iconSlate: '#94A3B8',
    iconGreenBg: '#064E3B',
    iconGreen: '#34D399',
    iconRedBg: '#7F1D1D',
    iconRed: '#F87171',
    iconOrangeBg: '#4C2A10',
    iconOrange: '#FFA066',
    iconPurpleBg: '#2E104C',
    iconPurple: '#A066FF',
    iconPinkBg: '#4C0825',
    iconPink: '#FF5E97',
    iconTealBg: '#0E4B46',
    iconTeal: '#4FD1C5',
    iconGrayBg: '#334155',
    iconGray: '#94A3B8',
    sheetBg: '#1E293B',
    sheetItemBg: '#0F172A',
    sheetDrag: '#475569',
    textPrimarySheet: '#60A5FA',
    textCancel: '#94A3B8',
    switchTrackFalse: '#475569',
    buttonText: '#fff',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: '#3B82F6',
  }
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
